### PR TITLE
MacOS Catalina Build working solution 

### PR DESCRIPTION
**Pull request by Pikachuxxxx**
I tried to rebuild it for catalina using the .air source file by tinkering it, please follow the steps mentioned in [How To Run On Catalina.md](https://github.com/Pikachuxxxx/boscaceoil/blob/master/How%20To%20Run%20On%20Catalina.md) to get it running and to know more on how I built it please read [Building V3 for Catalina.md](https://github.com/Pikachuxxxx/boscaceoil/blob/master/Building%20V3%20for%20Catalina.md).

Hope everyone can run the amazing BoscaCeoil with just a few extra clicks on Catalina now and I'll try to reduce the work even more in the near future.

 I was soo excited to get it running on my machine after a lot of failed trials, so if you've got any problems please feel free to open any issues and I'll try to help you resolve them .

Here's the [Working proof (Image)](https://github.com/Pikachuxxxx/boscaceoil/blob/master/Working%20Proof.png)

### CODE REVIEW

**Comment by TerryCavanagh** [comment]
Hey, this is very helpful, thank you! I'll merge this into the repo!

**Comment by RiceFarmerLenin** [comment]
Hello @TerryCavanagh ,

I am wondering when will the 64-bit version of Bosca Ceoil comes out. I would really like to use your app on my Mac Catalina for music for my future game developments. Thank you!

- RiceFarmerLenin

**Comment by Austin6-coder** [comment]
Thank U man

**Comment by RonanPseudonym** [comment]
Thank you so much!

**Pull request merged**
