### PR TITLE
Make escape ask before exiting

### PR DESCRIPTION
**Pull request by OShmuel255**
It was too annoying I had to change it

### CODE REVIEW

**Comment by Pikachuxxxx** [comment]
Wow the most required feature at last being implemented now, I wish this came earlier, with a lot of discrepancies in the software would make it hard to be accessible to everyone in the current times. But still thanks a lot for this one, you're saving us a lot of lost hours✌️✌️✌️✌️

**Comment by OShmuel255** [comment]
> Wow the most required feature at last being implemented now, I wish this came earlier, with a lot of discrepancies in the software would make it hard to be accessible to everyone in the current times. But still thanks a lot for this one, you're saving us a lot of lost hours✌️✌️✌️✌️

Crazy how it was so simple. I wonder why it wasn't added earlier...

**Comment by Pikachuxxxx** [comment]
> > Wow the most required feature at last being implemented now, I wish this came earlier, with a lot of discrepancies in the software would make it hard to be accessible to everyone in the current times. But still thanks a lot for this one, you're saving us a lot of lost hours✌️✌️✌️✌️
> 
> Crazy how it was so simple. I wonder why it wasn't added earlier...

could be the same reason why Blender 2.7 didn't have one, it's such an irony that the best of the softwares doesn't have the simplest things sometimes.

**Comment by david4444** [comment]
For those who want it
[swf.zip](https://github.com/TerryCavanagh/boscaceoil/files/4627149/swf.zip)

Just extract the swf to the bosca ceoil folder.

**Review by ghost — APPROVED** [review]

**Pull request closed without merging**
